### ISSUE TITLE
Languages support

### ISSUE THREAD

**Issue by Sid-Athos** [Kuinox/Kuinox-ARP#1]
Currently, the test to get IP adress is able to fail considering the language used by your OS "dynamic" french is "dynamique".

**Comment by Kuinox** [comment]
I think we may use Win32 api instead of supporting different languages, would cause less pain&bugs.

**Comment by Kuinox** [comment]
Anyway I don't want to support langages, pain and source of bugs, we should never deal with this at this level. Using win32 api look promising, and is more aligned with my dev beliefs.
